### ISSUE TITLE
Error on start -> ''"value" at position 0 fails because [child "name" fails because ["name" is required]].'

### ISSUE THREAD

**Issue by kkochanski** [danecando/hapi-sequelize#44]
Hello,

I'm using this packages with given versions:
hapi: 13.4.1
hapi-sequelize: 3.0.1
sequelize: 3.23.3
npm: 3.8.9
node: 6.2.0

On server start, I get this error:
`ValidationError: "value" at position 0 fails because [child "name" fails because ["name" is required]]. "value" must be an object
    at Object.exports.process (/home/kkochanski/Projects/default/social_media/node_modules/hapi-sequelize/node_modules/joi/lib/errors.js:152:19)
    at internals.Any._validateWithOptions (/home/kkochanski/Projects/default/social_media/node_modules/hapi-sequelize/node_modules/joi/lib/any.js:649:27)
    at root.validate (/home/kkochanski/Projects/default/social_media/node_modules/hapi-sequelize/node_modules/joi/lib/index.js:104:23)
    at Object.exports.register (/home/kkochanski/Projects/default/social_media/node_modules/hapi-sequelize/lib/index.js:49:26)
    at Object.target [as register] (/home/kkochanski/Projects/default/social_media/node_modules/hapi/node_modules/joi/lib/object.js:79:30)
    at each (/home/kkochanski/Projects/default/social_media/node_modules/hapi/lib/plugin.js:317:14)
    at iterate (/home/kkochanski/Projects/default/social_media/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at Object.exports.serial (/home/kkochanski/Projects/default/social_media/node_modules/hapi/node_modules/items/lib/index.js:39:9)
    at internals.Plugin.register (/home/kkochanski/Projects/default/social_media/node_modules/hapi/lib/plugin.js:320:11)
    at Object.<anonymous> (/home/kkochanski/Projects/default/social_media/server/server.js:41:8)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3
`

My `options` which are validated by `const validation = Joi.validate(options, Schema.options);`:
`[ { database: 'social_media',
    user: 'kkochanski',
    pass: null,
    dialect: 'mysql',
    port: 3306,
    models: 'db/models/*.js',
    sequelize: { define: [Object] } } ]
`

Right now I don't have any idea what's going wrong. It was working few days ago. Can anyone help?

**Comment by traducer** [comment]
@kkochanski You are currently running version 3.0.1 of `hapi-sequelize`. This will trip some people up because this version of hapi-sequelize is not merged into the master branch so the documentation is completely different.

If you look at the v3 branch you can see that the required options for the new version looks like this

```js
internals.option = exports.option = Joi.object().keys({
  name: Joi.string().token().required(),
  models: Joi.alternatives().try(Joi.string(), Joi.array().items(Joi.string())),
  sequelize: Joi.object().type(Sequelize).required(),
  sync: Joi.boolean().default(false),
  forceSync: Joi.boolean().default(false),
  debug: Joi.boolean()
});
```

Which can be found here https://github.com/danecando/hapi-sequelize/blob/v3/lib/schema.js#L9

be sure to switch to the v3 branch if you plan on using it, it's currently in beta and apparently hasn't been fully tested/implemented yet.

**Comment by kkochanski** [comment]
@traducer Thanks for your reply. I've just come back to v2 and it's working. Thanks ;)
