### ISSUE TITLE
I can't register plugin in Hapi 17

### ISSUE THREAD

**Issue by naijab** [danecando/hapi-sequelize#86]
I use hapi v.17, And I try to register this plugin. But it crash error in below. Please help me.

# Register Part.
```js
{
            register: require('hapi-sequelize'),
            options: {
              models: '**/models/**/*.js',
              sequelize: new Sequelize('db', 'root', '',
               {
                  host: 'localhost',
                  dialect: 'mysql',
                  pool: {
                    max: 5,
                    min: 0,
                    acquire: 30000,
                    idle: 10000
                  },
                 operatorsAliases: false
               }),
             sync: true,
              forceSync: false
            }
 }
```

# Error
```shell
TypeError: Method Set.prototype.values called on incompatible receiver #<Set>
    at Set.values (<anonymous>)
    at module.exports (/home/naijab/playground/hapi/japi/node_modules/core-js/modules/_for-of.js:19:33)
    at module.exports (/home/naijab/playground/hapi/japi/node_modules/core-js/modules/_array-from-iterable.js:5:3)
    at Set.toJSON (/home/naijab/playground/hapi/japi/node_modules/core-js/modules/_collection-to-json.js:7:12)
    at JSON.stringify (<anonymous>)
    at Object.internals.safeStringify (/home/naijab/playground/hapi/japi/node_modules/joi/lib/errors.js:209:17)
    at Error.internals.annotate (/home/naijab/playground/hapi/japi/node_modules/joi/lib/errors.js:347:29)
    at Object.exports.apply (/home/naijab/playground/hapi/japi/node_modules/hapi/lib/config.js:22:125)
    at internals.Server.register (/home/naijab/playground/hapi/japi/node_modules/hapi/lib/server.js:384:31)
    at _callee$ (/home/naijab/playground/hapi/japi/src/server.js:13:18)
    at tryCatch (/home/naijab/playground/hapi/japi/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/home/naijab/playground/hapi/japi/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/home/naijab/playground/hapi/japi/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/home/naijab/playground/hapi/japi/src/server.js:3:191)
    at /home/naijab/playground/hapi/japi/src/server.js:3:437
    at new Promise (<anonymous>)
    at /home/naijab/playground/hapi/japi/src/server.js:3:99
    at start (/home/naijab/playground/hapi/japi/src/server.js:11:7)
    at Object.<anonymous> (/home/naijab/playground/hapi/japi/src/server.js:43:1)
    at Module._compile (module.js:643:30)
    at loader (/home/naijab/playground/hapi/japi/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/naijab/playground/hapi/japi/node_modules/babel-register/lib/node.js:154:7)
```

**Comment by valtlfelipe** [comment]
Hi @naijab  

I have a fork with major fixes, and support for the latest hapi and sequelize versions.
Please have a look at https://github.com/valtlfelipe/hapi-sequelizejs.
